#include <vector>

#include "code.hpp"

namespace coap::test {

using TestValue = struct {
  struct {
    Code::Type type;
    std::vector<Code::Value> values;
    Code::Parts parts;
  } code;

  struct {
    bool is_request;
    bool is_response;
    bool is_success;
    bool is_client_error;
    bool is_server_error;
  } properties;
};

std::vector<TestValue> const kTestValues = {
    TestValue{.code = {.type = 0x00,
                       .values = {Code::Value::k000, Code::Value::kEmpty},
                       .parts = {.detail = 0, .class_ = Code::Class::kRequest}},
              .properties = {.is_request = true,
                             .is_response = false,
                             .is_success = false,
                             .is_client_error = false,
                             .is_server_error = false}},
    TestValue{.code = {.type = 0x01,
                       .values = {Code::Value::k001, Code::Value::kGet},
                       .parts = {.detail = 1, .class_ = Code::Class::kRequest}},
              .properties = {.is_request = true,
                             .is_response = false,
                             .is_success = false,
                             .is_client_error = false,
                             .is_server_error = false}},
    TestValue{.code = {.type = 0x02,
                       .values = {Code::Value::k002, Code::Value::kPost},
                       .parts = {.detail = 2, .class_ = Code::Class::kRequest}},
              .properties = {.is_request = true,
                             .is_response = false,
                             .is_success = false,
                             .is_client_error = false,
                             .is_server_error = false}},
    TestValue{.code = {.type = 0x03,
                       .values = {Code::Value::k003, Code::Value::kPut},
                       .parts = {.detail = 3, .class_ = Code::Class::kRequest}},
              .properties = {.is_request = true,
                             .is_response = false,
                             .is_success = false,
                             .is_client_error = false,
                             .is_server_error = false}},
    TestValue{.code = {.type = 0x04,
                       .values = {Code::Value::k004, Code::Value::kDelete},
                       .parts = {.detail = 4, .class_ = Code::Class::kRequest}},
              .properties = {.is_request = true,
                             .is_response = false,
                             .is_success = false,
                             .is_client_error = false,
                             .is_server_error = false}},

    TestValue{.code = {.type = 0x41,
                       .values = {Code::Value::k201},
                       .parts = {.detail = 1,
                                 .class_ = Code::Class::kResponseSuccess}},
              .properties = {.is_request = false,
                             .is_response = true,
                             .is_success = true,
                             .is_client_error = false,
                             .is_server_error = false}},
    TestValue{.code = {.type = 0x42,
                       .values = {Code::Value::k202},
                       .parts = {.detail = 2,
                                 .class_ = Code::Class::kResponseSuccess}},
              .properties = {.is_request = false,
                             .is_response = true,
                             .is_success = true,
                             .is_client_error = false,
                             .is_server_error = false}},
    TestValue{.code = {.type = 0x43,
                       .values = {Code::Value::k203},
                       .parts = {.detail = 3,
                                 .class_ = Code::Class::kResponseSuccess}},
              .properties = {.is_request = false,
                             .is_response = true,
                             .is_success = true,
                             .is_client_error = false,
                             .is_server_error = false}},
    TestValue{.code = {.type = 0x44,
                       .values = {Code::Value::k204},
                       .parts = {.detail = 4,
                                 .class_ = Code::Class::kResponseSuccess}},
              .properties = {.is_request = false,
                             .is_response = true,
                             .is_success = true,
                             .is_client_error = false,
                             .is_server_error = false}},
    TestValue{.code = {.type = 0x45,
                       .values = {Code::Value::k205},
                       .parts = {.detail = 5,
                                 .class_ = Code::Class::kResponseSuccess}},
              .properties = {.is_request = false,
                             .is_response = true,
                             .is_success = true,
                             .is_client_error = false,
                             .is_server_error = false}},

    TestValue{.code = {.type = 0x80,
                       .values = {Code::Value::k400},
                       .parts = {.detail = 0,
                                 .class_ = Code::Class::kResponseClientError}},
              .properties = {.is_request = false,
                             .is_response = true,
                             .is_success = false,
                             .is_client_error = true,
                             .is_server_error = false}},
    TestValue{.code = {.type = 0x81,
                       .values = {Code::Value::k401},
                       .parts = {.detail = 1,
                                 .class_ = Code::Class::kResponseClientError}},
              .properties = {.is_request = false,
                             .is_response = true,
                             .is_success = false,
                             .is_client_error = true,
                             .is_server_error = false}},
    TestValue{.code = {.type = 0x82,
                       .values = {Code::Value::k402},
                       .parts = {.detail = 2,
                                 .class_ = Code::Class::kResponseClientError}},
              .properties = {.is_request = false,
                             .is_response = true,
                             .is_success = false,
                             .is_client_error = true,
                             .is_server_error = false}},
    TestValue{.code = {.type = 0x83,
                       .values = {Code::Value::k403},
                       .parts = {.detail = 3,
                                 .class_ = Code::Class::kResponseClientError}},
              .properties = {.is_request = false,
                             .is_response = true,
                             .is_success = false,
                             .is_client_error = true,
                             .is_server_error = false}},
    TestValue{.code = {.type = 0x84,
                       .values = {Code::Value::k404},
                       .parts = {.detail = 4,
                                 .class_ = Code::Class::kResponseClientError}},
              .properties = {.is_request = false,
                             .is_response = true,
                             .is_success = false,
                             .is_client_error = true,
                             .is_server_error = false}},
    TestValue{.code = {.type = 0x85,
                       .values = {Code::Value::k405},
                       .parts = {.detail = 5,
                                 .class_ = Code::Class::kResponseClientError}},
              .properties = {.is_request = false,
                             .is_response = true,
                             .is_success = false,
                             .is_client_error = true,
                             .is_server_error = false}},
    TestValue{.code = {.type = 0x86,
                       .values = {Code::Value::k406},
                       .parts = {.detail = 6,
                                 .class_ = Code::Class::kResponseClientError}},
              .properties = {.is_request = false,
                             .is_response = true,
                             .is_success = false,
                             .is_client_error = true,
                             .is_server_error = false}},
    TestValue{.code = {.type = 0x8c,
                       .values = {Code::Value::k412},
                       .parts = {.detail = 12,
                                 .class_ = Code::Class::kResponseClientError}},
              .properties = {.is_request = false,
                             .is_response = true,
                             .is_success = false,
                             .is_client_error = true,
                             .is_server_error = false}},
    TestValue{.code = {.type = 0x8d,
                       .values = {Code::Value::k413},
                       .parts = {.detail = 13,
                                 .class_ = Code::Class::kResponseClientError}},
              .properties = {.is_request = false,
                             .is_response = true,
                             .is_success = false,
                             .is_client_error = true,
                             .is_server_error = false}},
    TestValue{.code = {.type = 0x8f,
                       .values = {Code::Value::k415},
                       .parts = {.detail = 15,
                                 .class_ = Code::Class::kResponseClientError}},
              .properties = {.is_request = false,
                             .is_response = true,
                             .is_success = false,
                             .is_client_error = true,
                             .is_server_error = false}},

    TestValue{.code = {.type = 0xa0,
                       .values = {Code::Value::k500},
                       .parts = {.detail = 0,
                                 .class_ = Code::Class::kResponseServerError}},
              .properties = {.is_request = false,
                             .is_response = true,
                             .is_success = false,
                             .is_client_error = false,
                             .is_server_error = true}},
    TestValue{.code = {.type = 0xa1,
                       .values = {Code::Value::k501},
                       .parts = {.detail = 1,
                                 .class_ = Code::Class::kResponseServerError}},
              .properties = {.is_request = false,
                             .is_response = true,
                             .is_success = false,
                             .is_client_error = false,
                             .is_server_error = true}},
    TestValue{.code = {.type = 0xa2,
                       .values = {Code::Value::k502},
                       .parts = {.detail = 2,
                                 .class_ = Code::Class::kResponseServerError}},
              .properties = {.is_request = false,
                             .is_response = true,
                             .is_success = false,
                             .is_client_error = false,
                             .is_server_error = true}},
    TestValue{.code = {.type = 0xa3,
                       .values = {Code::Value::k503},
                       .parts = {.detail = 3,
                                 .class_ = Code::Class::kResponseServerError}},
              .properties = {.is_request = false,
                             .is_response = true,
                             .is_success = false,
                             .is_client_error = false,
                             .is_server_error = true}},
    TestValue{.code = {.type = 0xa4,
                       .values = {Code::Value::k504},
                       .parts = {.detail = 4,
                                 .class_ = Code::Class::kResponseServerError}},
              .properties = {.is_request = false,
                             .is_response = true,
                             .is_success = false,
                             .is_client_error = false,
                             .is_server_error = true}},
    TestValue{.code = {.type = 0xa5,
                       .values = {Code::Value::k505},
                       .parts = {.detail = 5,
                                 .class_ = Code::Class::kResponseServerError}},
              .properties = {.is_request = false,
                             .is_response = true,
                             .is_success = false,
                             .is_client_error = false,
                             .is_server_error = true}},
};

}  // namespace coap::test
